# Generated by Django 5.2.7 on 2025-10-14 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gabinete",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.TextField(verbose_name="Descripción")),
            ],
        ),
        migrations.CreateModel(
            name="Laboratorio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.TextField(verbose_name="Descripción")),
            ],
        ),
        migrations.RemoveField(
            model_name="historiaclinica",
            name="id_servicio",
        ),
        migrations.CreateModel(
            name="ExpedienteClinico",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_historia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.historiaclinica",
                        verbose_name="Historia Clínica",
                    ),
                ),
                (
                    "id_paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.paciente",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "id_gabinete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.gabinete",
                        verbose_name="Gabinete",
                    ),
                ),
                (
                    "id_laboratorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.laboratorio",
                        verbose_name="Laboratorio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroGabinete",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("tomografia", "Tomografía"),
                            ("ecografia", "Ecografía"),
                        ],
                        max_length=100,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(verbose_name="Fecha de Registro"),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "gabinete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.gabinete",
                        verbose_name="Gabinete",
                    ),
                ),
                (
                    "personal_salud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.personalsalud",
                        verbose_name="Personal de Salud",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroLaboratorio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("sangre", "Sangre"),
                            ("orina", "Orina"),
                            ("heces", "Heces"),
                        ],
                        max_length=100,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "laboratorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.laboratorio",
                        verbose_name="Laboratorio",
                    ),
                ),
                (
                    "personal_salud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.personalsalud",
                        verbose_name="Personal de Salud",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AtencionMedica",
        ),
        migrations.DeleteModel(
            name="Servicio",
        ),
    ]
