# Generated by Django 5.2.7 on 2025-10-14 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_gabinete_laboratorio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paciente",
            name="correo",
        ),
    ]
