# Generated by Django 5.2.7 on 2025-10-14 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_paciente_correo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expedienteclinico",
            name="id_gabinete",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.gabinete",
                verbose_name="Gabinete",
            ),
        ),
        migrations.AlterField(
            model_name="expedienteclinico",
            name="id_historia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.historiaclinica",
                verbose_name="Historia Clínica",
            ),
        ),
        migrations.AlterField(
            model_name="expedienteclinico",
            name="id_laboratorio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.laboratorio",
                verbose_name="Laboratorio",
            ),
        ),
        migrations.AlterField(
            model_name="expedienteclinico",
            name="id_paciente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.paciente",
                verbose_name="Paciente",
            ),
        ),
    ]
