# Generated by Django 5.2.7 on 2025-10-15 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_expedienteclinico_id_gabinete_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitaMedica",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_cita", models.DateTimeField(verbose_name="Fecha de Cita")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                ("nota", models.TextField(verbose_name="Nota")),
                (
                    "historia_clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.historiaclinica",
                        verbose_name="Historia Clínica",
                    ),
                ),
                (
                    "id_profesional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.personalsalud",
                        verbose_name="Profesional de Salud",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cita Médica",
                "verbose_name_plural": "Citas Médicas",
                "db_table": "cita_medica",
            },
        ),
    ]
