# Generated by Django 5.2.7 on 2025-10-15 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_citamedica"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historiaclinica",
            old_name="observaciones",
            new_name="observaciones_ingreso",
        ),
        migrations.RemoveField(
            model_name="historiaclinica",
            name="diagnostico",
        ),
        migrations.RemoveField(
            model_name="historiaclinica",
            name="motivo_consulta",
        ),
    ]
