# Generated by Django 5.2.7 on 2025-10-15 00:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0006_rename_observaciones_historiaclinica_observaciones_ingreso_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HojaIngreso",
            fields=[
                (
                    "id_hoja_ingreso",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "fecha_ingreso",
                    models.DateTimeField(verbose_name="Fecha de Ingreso"),
                ),
                (
                    "observaciones_ingreso",
                    models.TextField(verbose_name="Observaciones de Ingreso"),
                ),
                ("peso", models.FloatField(verbose_name="Peso")),
                ("talla", models.FloatField(verbose_name="Talla")),
                (
                    "presion_arterial",
                    models.FloatField(verbose_name="Presión Arterial"),
                ),
                (
                    "frecuencia_cardiaca",
                    models.FloatField(verbose_name="Frecuencia Cardiaca"),
                ),
                (
                    "frecuencia_respiratoria",
                    models.FloatField(verbose_name="Frecuencia Respiratoria"),
                ),
                ("temperatura", models.FloatField(verbose_name="Temperatura")),
                (
                    "saturacion_oxigeno",
                    models.FloatField(verbose_name="Saturación de Oxígeno"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="historiaclinica",
            name="fecha_alta",
        ),
        migrations.RemoveField(
            model_name="historiaclinica",
            name="observaciones_ingreso",
        ),
        migrations.AddField(
            model_name="historiaclinica",
            name="fecha_actualizacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de Actualización"
            ),
        ),
        migrations.AddField(
            model_name="historiaclinica",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha de Creación",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="citamedica",
            name="hoja_ingreso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.hojaingreso",
                verbose_name="Hoja de Ingreso",
            ),
        ),
    ]
