# Generated by Django 5.2.7 on 2025-10-15 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_hojaingreso_remove_historiaclinica_fecha_alta_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordenmedica",
            name="id_episodio",
        ),
        migrations.RemoveField(
            model_name="resultadoclinico",
            name="id_orden",
        ),
        migrations.DeleteModel(
            name="EvolucionClinica",
        ),
        migrations.DeleteModel(
            name="OrdenMedica",
        ),
        migrations.DeleteModel(
            name="ResultadoClinico",
        ),
    ]
